variables:
  random_state: 42
  vocab_size: 30522
  ngram_range: (3, 5)
  sublinear_tf: True
  lowercase: False
  max_features: 5000


data:
  preprocessed_train_data_path: data/interim/full_train.csv
  preprocessed_test_data_path: data/interim/full_test.csv
  processed_train_data_path: data/processed/train.csv
  processed_test_data_path: data/processed/test.csv
  sentpiece_train_data_path: data/interim/sentpiece_train.txt

models:
  sentpiece_model_prefix: models/sentpiece_model
  vectorizer_path: models/tfidf_vectorizer.pkl