variables:
  random_state: 42
  test_size: 0.5
  vocab_size: 30522
  ngram_range: (3, 5)
  sublinear_tf: True
  lowercase: False
  max_features: 5000
  n_trials: 20

data:
  preprocessed_train_data_path: data/interim/full_train.csv
  preprocessed_test_data_path: data/interim/full_test.csv
  processed_train_data_path: data/processed/train.csv
  processed_test_data_path: data/processed/test.csv
  sentpiece_train_data_path: data/interim/sentpiece_train.txt
  modelling_X_train_data_path: data/modelling/train.npy
  modelling_X_test_data_path: data/modelling/test.npy
  modelling_X_validation_data_path: data/modelling/validation.npy
  modelling_y_train_data_path: data/modelling/train.csv
  modelling_y_test_data_path: data/modelling/test.csv
  modelling_y_validation_data_path: data/modelling/validation.csv

models:
  sentpiece_model_prefix: models/sentpiece_model
  sentpiece_model_path: models/sentpiece_model.model
  vectorizer_path: models/tfidf_vectorizer.pkl
  hyperparameters_path: models/hyperparameters.json

mlflow:
  experiment_name: "detect-ai-text"
  tracking_uri: "http://localhost:5000"
  artifact_location: "artifacts"

hyperparameter_tuning_lgbm:
  objective: cross_entropy
  metric: custom
  n_iter: 2500
  verbose: -1
  min_data_in_leaf: [50, 150]
  max_depth: [10, 30]
  max_bin: [500, 1000]
  learning_rate: [0.001, 0.1]
  colsample_bytree: [0.7, 1.0]
  colsample_bynode: [0.7, 1.0]
  lambda_l1: [0.1, 10]
  lambda_l2: [0.1, 10]
